// <auto-generated />
using System;
using EmployeeManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeeManagement.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240717125426_second")]
    partial class second
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("EmployeeManagement.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Salary")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/227.jpg",
                            Name = "Augustus Lindgren",
                            Position = 2,
                            Salary = 31478m,
                            Type = 3
                        },
                        new
                        {
                            Id = 2,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1048.jpg",
                            Name = "Yvette Lueilwitz",
                            Position = 4,
                            Salary = 94515m,
                            Type = 2
                        },
                        new
                        {
                            Id = 3,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/776.jpg",
                            Name = "Brando Satterfield",
                            Position = 2,
                            Salary = 57270m,
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/55.jpg",
                            Name = "Zoila Lynch",
                            Position = 7,
                            Salary = 44672m,
                            Type = 3
                        },
                        new
                        {
                            Id = 5,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1119.jpg",
                            Name = "Rey Renner",
                            Position = 1,
                            Salary = 87964m,
                            Type = 3
                        },
                        new
                        {
                            Id = 6,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1183.jpg",
                            Name = "Maria Reynolds",
                            Position = 7,
                            Salary = 93040m,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/118.jpg",
                            Name = "Jaren Baumbach",
                            Position = 5,
                            Salary = 49981m,
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1020.jpg",
                            Name = "Kolby Lang",
                            Position = 3,
                            Salary = 34933m,
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/413.jpg",
                            Name = "Mireille Crooks",
                            Position = 2,
                            Salary = 45219m,
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/398.jpg",
                            Name = "Beth Zemlak",
                            Position = 3,
                            Salary = 63662m,
                            Type = 3
                        },
                        new
                        {
                            Id = 11,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1050.jpg",
                            Name = "Concepcion McGlynn",
                            Position = 8,
                            Salary = 92418m,
                            Type = 2
                        },
                        new
                        {
                            Id = 12,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/234.jpg",
                            Name = "Kristin Kris",
                            Position = 6,
                            Salary = 60649m,
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/274.jpg",
                            Name = "Taylor Langworth",
                            Position = 4,
                            Salary = 64620m,
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/203.jpg",
                            Name = "Romaine Dooley",
                            Position = 9,
                            Salary = 72751m,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1058.jpg",
                            Name = "Samir Prosacco",
                            Position = 1,
                            Salary = 87926m,
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/418.jpg",
                            Name = "Damon Schiller",
                            Position = 9,
                            Salary = 39440m,
                            Type = 1
                        },
                        new
                        {
                            Id = 17,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/996.jpg",
                            Name = "Zoila O'Hara",
                            Position = 8,
                            Salary = 41300m,
                            Type = 3
                        },
                        new
                        {
                            Id = 18,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1057.jpg",
                            Name = "Porter Nicolas",
                            Position = 9,
                            Salary = 35555m,
                            Type = 1
                        },
                        new
                        {
                            Id = 19,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/27.jpg",
                            Name = "Blanche Reynolds",
                            Position = 2,
                            Salary = 66840m,
                            Type = 1
                        },
                        new
                        {
                            Id = 20,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/108.jpg",
                            Name = "Name Stoltenberg",
                            Position = 7,
                            Salary = 42450m,
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/712.jpg",
                            Name = "Dorris Klocko",
                            Position = 1,
                            Salary = 38195m,
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/918.jpg",
                            Name = "Crystel Kovacek",
                            Position = 7,
                            Salary = 93319m,
                            Type = 3
                        },
                        new
                        {
                            Id = 23,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/819.jpg",
                            Name = "Carlie Heller",
                            Position = 3,
                            Salary = 62350m,
                            Type = 2
                        },
                        new
                        {
                            Id = 24,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/851.jpg",
                            Name = "Damien Bahringer",
                            Position = 1,
                            Salary = 69856m,
                            Type = 1
                        },
                        new
                        {
                            Id = 25,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/416.jpg",
                            Name = "Eleanora Ullrich",
                            Position = 1,
                            Salary = 77225m,
                            Type = 3
                        },
                        new
                        {
                            Id = 26,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/806.jpg",
                            Name = "Madison Batz",
                            Position = 5,
                            Salary = 90334m,
                            Type = 1
                        },
                        new
                        {
                            Id = 27,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/70.jpg",
                            Name = "Diego Steuber",
                            Position = 5,
                            Salary = 86762m,
                            Type = 2
                        },
                        new
                        {
                            Id = 28,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1029.jpg",
                            Name = "Alden Kozey",
                            Position = 2,
                            Salary = 97808m,
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1191.jpg",
                            Name = "Bobbie Feeney",
                            Position = 3,
                            Salary = 90579m,
                            Type = 3
                        },
                        new
                        {
                            Id = 30,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/676.jpg",
                            Name = "Della Towne",
                            Position = 6,
                            Salary = 94605m,
                            Type = 2
                        },
                        new
                        {
                            Id = 31,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/383.jpg",
                            Name = "Mercedes Parker",
                            Position = 9,
                            Salary = 96780m,
                            Type = 2
                        },
                        new
                        {
                            Id = 32,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1086.jpg",
                            Name = "Helen Considine",
                            Position = 3,
                            Salary = 42790m,
                            Type = 3
                        },
                        new
                        {
                            Id = 33,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1237.jpg",
                            Name = "Kenya Jones",
                            Position = 0,
                            Salary = 46324m,
                            Type = 2
                        },
                        new
                        {
                            Id = 34,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/947.jpg",
                            Name = "Peggie Stoltenberg",
                            Position = 6,
                            Salary = 34128m,
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/490.jpg",
                            Name = "Makenna O'Keefe",
                            Position = 2,
                            Salary = 40889m,
                            Type = 1
                        },
                        new
                        {
                            Id = 36,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1036.jpg",
                            Name = "Christ Hartmann",
                            Position = 0,
                            Salary = 73000m,
                            Type = 0
                        },
                        new
                        {
                            Id = 37,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/159.jpg",
                            Name = "Lincoln Mayer",
                            Position = 2,
                            Salary = 95724m,
                            Type = 3
                        },
                        new
                        {
                            Id = 38,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/298.jpg",
                            Name = "King Gislason",
                            Position = 8,
                            Salary = 77193m,
                            Type = 3
                        },
                        new
                        {
                            Id = 39,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/629.jpg",
                            Name = "Niko Mante",
                            Position = 7,
                            Salary = 33700m,
                            Type = 3
                        },
                        new
                        {
                            Id = 40,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1176.jpg",
                            Name = "Casandra Kilback",
                            Position = 2,
                            Salary = 91588m,
                            Type = 2
                        },
                        new
                        {
                            Id = 41,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/792.jpg",
                            Name = "Larissa Hoppe",
                            Position = 0,
                            Salary = 71070m,
                            Type = 0
                        },
                        new
                        {
                            Id = 42,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/790.jpg",
                            Name = "Sincere Senger",
                            Position = 2,
                            Salary = 36830m,
                            Type = 1
                        },
                        new
                        {
                            Id = 43,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/622.jpg",
                            Name = "Julia Zieme",
                            Position = 9,
                            Salary = 38937m,
                            Type = 1
                        },
                        new
                        {
                            Id = 44,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/479.jpg",
                            Name = "Ethel Bednar",
                            Position = 7,
                            Salary = 96833m,
                            Type = 1
                        },
                        new
                        {
                            Id = 45,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/450.jpg",
                            Name = "Taya Corwin",
                            Position = 0,
                            Salary = 53861m,
                            Type = 2
                        },
                        new
                        {
                            Id = 46,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/3.jpg",
                            Name = "Daphney Pacocha",
                            Position = 2,
                            Salary = 32417m,
                            Type = 1
                        },
                        new
                        {
                            Id = 47,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1113.jpg",
                            Name = "Yolanda Sporer",
                            Position = 4,
                            Salary = 49028m,
                            Type = 0
                        },
                        new
                        {
                            Id = 48,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1054.jpg",
                            Name = "Jimmy Hahn",
                            Position = 0,
                            Salary = 67034m,
                            Type = 2
                        },
                        new
                        {
                            Id = 49,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/265.jpg",
                            Name = "Reese Champlin",
                            Position = 6,
                            Salary = 86243m,
                            Type = 3
                        },
                        new
                        {
                            Id = 50,
                            ImgUrl = "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/648.jpg",
                            Name = "Augustus Schmeler",
                            Position = 4,
                            Salary = 87890m,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
